common: &default_settings
  license_key: '0a0d3776322392d64886579d8e72499290edd79a'
  app_name: icasmailing
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  # verify_certificate: true
  # http://support.newrelic.com/faqs/general/apdex
  apdex_t: 0.5
  # proxy_host: hostname
  # proxy_port: 8080
  # proxy_user:
  # proxy_pass:
  capture_params: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    # explain_enabled: true
    # explain_threshold: 0.5
  error_collector:
    enabled: true
    capture_source: true    
    ignore_errors: ActionController::RoutingError

  # disable_samplers: true
  # disable_view_instrumentation: true
  # disable_activerecord_instrumentation: true
  # disable_memcache_instrumentation: true
  # disable_dj: true
  # multi_threaded = false

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true
  # textmate: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: icasmailing (Staging)
